<?php

$musicas = [
    ["titulo"=>"Numb","artista"=>"Linkin Park","genero"=>"Rock","ano"=>2003],
    ["titulo"=>"In The End","artista"=>"Linkin Park","genero"=>"Rock","ano"=>2000],
    ["titulo"=>"Bohemian Rhapsody","artista"=>"Queen","genero"=>"Rock","ano"=>1975],
    ["titulo"=>"Billie Jean","artista"=>"Michael Jackson","genero"=>"Pop","ano"=>1982],
    ["titulo"=>"Smells Like Teen Spirit","artista"=>"Nirvana","genero"=>"Grunge","ano"=>1991],
    ["titulo"=>"Imagine","artista"=>"John Lennon","genero"=>"Rock","ano"=>1971],
    ["titulo"=>"Hey Jude","artista"=>"The Beatles","genero"=>"Rock","ano"=>1968],
    ["titulo"=>"Thriller","artista"=>"Michael Jackson","genero"=>"Pop","ano"=>1982],
    ["titulo"=>"Like a Rolling Stone","artista"=>"Bob Dylan","genero"=>"Folk","ano"=>1965],
    ["titulo"=>"Hotel California","artista"=>"Eagles","genero"=>"Rock","ano"=>1976],

    ["titulo"=>"Wonderwall","artista"=>"Oasis","genero"=>"Rock","ano"=>1995],
    ["titulo"=>"Lose Yourself","artista"=>"Eminem","genero"=>"Rap","ano"=>2002],
    ["titulo"=>"Rolling in the Deep","artista"=>"Adele","genero"=>"Pop","ano"=>2010],
    ["titulo"=>"Fix You","artista"=>"Coldplay","genero"=>"Rock","ano"=>2005],
    ["titulo"=>"Hallelujah","artista"=>"Jeff Buckley","genero"=>"Folk","ano"=>1994],
    ["titulo"=>"Creep","artista"=>"Radiohead","genero"=>"Rock","ano"=>1992],
    ["titulo"=>"Viva La Vida","artista"=>"Coldplay","genero"=>"Rock","ano"=>2008],
    ["titulo"=>"Chop Suey","artista"=>"System of a Down","genero"=>"Metal","ano"=>2001],
    ["titulo"=>"Enter Sandman","artista"=>"Metallica","genero"=>"Metal","ano"=>1991],
    ["titulo"=>"Seven Nation Army","artista"=>"The White Stripes","genero"=>"Rock","ano"=>2003],

    ["titulo"=>"Take On Me","artista"=>"A-ha","genero"=>"Pop","ano"=>1985],
    ["titulo"=>"Sweet Child O' Mine","artista"=>"Guns N' Roses","genero"=>"Rock","ano"=>1987],
    ["titulo"=>"Zombie","artista"=>"The Cranberries","genero"=>"Rock","ano"=>1994],
    ["titulo"=>"Blinding Lights","artista"=>"The Weeknd","genero"=>"Pop","ano"=>2019],
    ["titulo"=>"Shape of You","artista"=>"Ed Sheeran","genero"=>"Pop","ano"=>2017],
    ["titulo"=>"Bad Guy","artista"=>"Billie Eilish","genero"=>"Pop","ano"=>2019],
    ["titulo"=>"Uptown Funk","artista"=>"Bruno Mars","genero"=>"Funk","ano"=>2014],
    ["titulo"=>"Let It Be","artista"=>"The Beatles","genero"=>"Rock","ano"=>1970],
    ["titulo"=>"Yesterday","artista"=>"The Beatles","genero"=>"Rock","ano"=>1965],
    ["titulo"=>"Thunderstruck","artista"=>"AC/DC","genero"=>"Rock","ano"=>1990],

    ["titulo"=>"Nothing Else Matters","artista"=>"Metallica","genero"=>"Metal","ano"=>1992],
    ["titulo"=>"Back in Black","artista"=>"AC/DC","genero"=>"Rock","ano"=>1980],
    ["titulo"=>"Time","artista"=>"Pink Floyd","genero"=>"Rock","ano"=>1973],
    ["titulo"=>"Comfortably Numb","artista"=>"Pink Floyd","genero"=>"Rock","ano"=>1979],
    ["titulo"=>"Stairway to Heaven","artista"=>"Led Zeppelin","genero"=>"Rock","ano"=>1971],
    ["titulo"=>"Dream On","artista"=>"Aerosmith","genero"=>"Rock","ano"=>1973],
    ["titulo"=>"Californication","artista"=>"Red Hot Chili Peppers","genero"=>"Rock","ano"=>1999],
    ["titulo"=>"Otherside","artista"=>"Red Hot Chili Peppers","genero"=>"Rock","ano"=>1999],
    ["titulo"=>"Black","artista"=>"Pearl Jam","genero"=>"Grunge","ano"=>1991],
    ["titulo"=>"Alive","artista"=>"Pearl Jam","genero"=>"Grunge","ano"=>1991],

    ["titulo"=>"Radioactive","artista"=>"Imagine Dragons","genero"=>"Rock","ano"=>2012],
    ["titulo"=>"Demons","artista"=>"Imagine Dragons","genero"=>"Rock","ano"=>2013],
    ["titulo"=>"Believer","artista"=>"Imagine Dragons","genero"=>"Rock","ano"=>2017],
    ["titulo"=>"Nights","artista"=>"Frank Ocean","genero"=>"R&B","ano"=>2016],
    ["titulo"=>"Thinking Out Loud","artista"=>"Ed Sheeran","genero"=>"Pop","ano"=>2014],
    ["titulo"=>"Someone Like You","artista"=>"Adele","genero"=>"Pop","ano"=>2011],
    ["titulo"=>"Skyfall","artista"=>"Adele","genero"=>"Pop","ano"=>2012],
    ["titulo"=>"Counting Stars","artista"=>"OneRepublic","genero"=>"Pop","ano"=>2013],
    ["titulo"=>"Apologize","artista"=>"OneRepublic","genero"=>"Pop","ano"=>2007],
    ["titulo"=>"Under the Bridge","artista"=>"Red Hot Chili Peppers","genero"=>"Rock","ano"=>1992],
];